##Q1

In [1]:
import numpy as np
x = np.array([[-3.2, 4.1, 0.163]])
w1 = np.array([[0.1, 0.3],[0.2, 0.4], [0.5, 0.6]])
o1 = np.dot(x, w1)
print(o1)

[[0.5815 0.7778]]


In [2]:
def Sigmoid(a):
  h = 1/(1+np.exp(a))
  return h

In [3]:
def Tanh(a):
  c = np.exp(a)
  d = np.exp(-1*a)
  h = (d-c)/(d+c)
  return h

In [4]:
def Relu(a):
  h = a
  for i in range(len(h.T)):
    if(h[0][i]<0):
      h[0][i] = 0
  return h

In [5]:
h1 = Sigmoid(o1)
print(h1)

[[0.35858752 0.31479423]]


In [6]:
w2 = np.array([[0.7],[0.8]])
y = np.dot(h1, w2)
print(y)

[[0.50284665]]


In [7]:
h1 = Tanh(o1)
print(h1)

[[-0.52375481 -0.65144215]]


In [8]:
y = np.dot(h1, w2)
print(y)

[[-0.88778208]]


In [9]:
h1 = Relu(o1)
print(h1)

[[0.5815 0.7778]]


In [10]:
y = np.dot(h1, w2)
print(y)

[[1.02929]]


##Q3

In [11]:
x = np.array([[-3.2, 4.1, 0.163],[-1.7, 3.9, 1.35],[-4.16, 4.33, 0.78],[-2.73, 3.14, 1.07]])
w1 = np.array([[0.1, 0.3],[0.2, 0.4], [0.5, 0.6]])
N_iteration = 1
alpha = 0.05
o1 = np.dot(x, w1)
h1 = Sigmoid(o1)
w2 = np.array([[0.7],[0.8]])
y_hat = np.dot(h1, w2)
print(y_hat)

[[0.50284665]
 [0.25945266]
 [0.43386058]
 [0.40673312]]


In [12]:
y = np.array([[2],[6.2],[3.5],[4.2]])
e = y_hat-y
print(e)

[[-1.49715335]
 [-5.94054734]
 [-3.06613942]
 [-3.79326688]]


In [13]:
def Diff(w1, w2, o1):
  c = np.exp(o1)
  d = c/pow((c+1),2)
  print(d.shape)
  w_2 = np.hstack((w2, w2, w2))
  d = np.sum(d, axis = 0)
  print(d.shape)
  D = np.vstack((d, d, d))
  print(D.shape)
  ans = D*np.multiply(w1, w_2.T)
  return ans

In [14]:
E = np.hstack((e,e))
w2_new = w2-2*alpha*np.sum((np.multiply(E, h1).T), axis = 1)
w1_new = w1-2*alpha*np.sum(e)* Diff(w1, w2, o1)
print(w2_new)
print('*'*100)
print(w1_new)

(4, 2)
(2,)
(3, 2)
[[1.08529839 1.00877061]
 [1.18529839 1.10877061]]
****************************************************************************************************
[[0.18173716 0.54791907]
 [0.36347432 0.73055876]
 [0.90868579 1.09583814]]
